name: integration
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Integration
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python datapipeline.py
	  add . 
          git commit -m "New Commit in Integration on `date +'%Y-%m-%d %H:%M:%S'`" 
          git push origin Integration	
          #cat metrics.txt >> report.md
          #cml-publish plot.png --md >> report.md
          #cml-send-comment report.md
